stages:
  - Build homepage
  - Deploy

build:
  stage: Build homepage
  script:
    - npm install
    - npm run build
      
deploy:
  stage: Deploy
  script: 
    - pm2 deploy configs/ecosystem.config.js dev
  dependencies:
    - build
