stages:
  - Build homepage
  - Deploy

build:
  stage: Build homepage
  script:
    - npm install
    - npm run build

check coding style: 
  stage: Build homepage
  script:
    - npm install
    - npm run lint
  allow_failure: true
      
deploy:
  stage: Deploy
  script:
    - source $HOME/.profile
    - pm2 deploy scripts/ecosystem.config.js dev
  dependencies:
    - build
