stages:
  - Build homepage
  - Deploy

build:
  stage: Build homepage
  script:
    - npm install
    - npm run build
  artifacts:
    paths: 
      - dist

check coding style: 
  stage: Build homepage
  script:
    - npm install
    - npm run lint
  allow_failure: true
      
deploy to dev server:
  stage: Deploy
  only:
    - dev
  script:
    - pm2 deploy scripts/ecosystem.config.js dev
  dependencies:
    - build

deploy to production server:
  stage: Deploy
  only:
    - master
  script:
    - pm2 deploy scripts/ecosystem.config.js production
  dependencies:
    - build
