#!/bin/bash

echo 'Ensure the coding style is correct...'

CHANGED_FILE=$(git diff --cached --name-only)

for file in $CHANGED_FILE; do
    if [[ ( $file == *.js ) || ( $file == *.vue ) ]] 
    then
        if ! eslint --no-ignore $file 2> /dev/null;
        then
            echo "Coding style checking failed in $file, please run 'npm run style' to fix it."
            exit 1
        fi
    fi
done

echo 'Congratulations, you can commit now!'
